osx_image: xcode7.1
language: objective-c
cache: cocoapods
before_install:
    - bundle install
    - bundle exec pod install --project-directory=Example
script:
    - bundle exec rake spec
after_success:
    - bundle exec slather
